In [2]:
import tensorflow as tf

In [14]:
p = tf.placeholder('float', None)

In [15]:
operacao = p + 2

In [16]:
with tf.Session() as sess:
    #sess.run(operacao)
    resultado = sess.run(operacao, feed_dict = {p: [1, 2, 3]})
    print(resultado)

[3. 4. 5.]


In [19]:
p2 = tf.placeholder('float', [None, 5])
operacao2 = p2 * 5

In [20]:
with tf.Session() as sess:
    dados = [[1,2,3,4,5], [6,7,8,9,10]]
    resultado = sess.run(operacao2, feed_dict={p2: dados})
    print(resultado)

[[ 5. 10. 15. 20. 25.]
 [30. 35. 40. 45. 50.]]
