In [1]:
import tensorflow as tf

In [2]:
a = tf.constant((9, 8, 7), name='a')
b = tf.constant((1, 2, 3), name='b')

In [3]:
soma = a + b

In [4]:
with tf.Session() as sess:
    print(sess.run(soma))

[10 10 10]


In [5]:
a1 = tf.constant([[1, 2, 3],[4, 5, 6]], name='a1')

In [7]:
type(a1)

Tensor("a1:0", shape=(2, 3), dtype=int32)


In [8]:
print(a1)

Tensor("a1:0", shape=(2, 3), dtype=int32)


In [9]:
a1.shape

TensorShape([Dimension(2), Dimension(3)])

In [10]:
b1 = tf.constant([[1, 2, 3],[4, 5, 6]], name='b1')

In [11]:
soma1 = tf.add(a1,b1)

In [13]:
with tf.Session() as sess:
    print(sess.run(soma1))

[[ 2  4  6]
 [ 8 10 12]]


In [16]:
a2 = tf.constant([[1,2,3],[4,5,6]])
b2 = tf.constant([[1],[2]])
soma2 = tf.add(a2,b2)

In [18]:
with tf.Session() as sess:
    print(sess.run(a2))
    print('\n')
    print(sess.run(b2))
    print('\n')
    print(sess.run(soma2))
    

[[1 2 3]
 [4 5 6]]


[[1]
 [2]]


[[2 3 4]
 [6 7 8]]
